#!/bin/sh
### BEGIN INIT INFO
# Provides:		cgmi-daemon-0.10
# Required-Start:	$nxserver 
# Required-Stop:	
# Default-Start:	2 3 4 5
# Default-Stop:		1
# Short-Description:	CGMI 
### END INIT INFO
#
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/cgmi-daemon-0.10
NAME=cgmi-daemon-0.10
DESC="Cisco Gstreamer Media Interface "

DBUS_SESSION_ADDR='/var/run/dbus/SessionBusAddress.txt'


if [ ! -e "$DBUS_SESSION_ADDR" ]
then
	echo "Error starting $DAEMON.  Couldn't find dbus session address. Is dbus running?"
	exit 1
fi

export DBUS_SESSION_BUS_ADDRESS=$(cat $DBUS_SESSION_ADDR)


set -e



case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon -S \
	  -x "$DAEMON"  
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x "$DAEMON"
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon -K -x "$DAEMON"
	sleep 1
	start-stop-daemon -S \
	  -x "$DAEMON" 
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
